name: CI

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:

      - name: Baixa o repositório
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instala dependências
        run: pip install ruff sqlfluff sqlfluff-templater-dbt dbt-duckdb

      - name: Lint Python
        run: ruff check .

      - name: Lint SQL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: sqlfluff lint airflow/include/dbt_gold/models --profiles-dir .github/profiles

      - name: dbt compile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: dbt compile --project-dir airflow/include/dbt_gold --profiles-dir .github/profiles